package form;


import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import controler.StudentModify;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class DocGia extends javax.swing.JFrame {
     DefaultTableModel tableModel;
        List<qltv.DocGia> DocGiaList = new ArrayList<>();
    /**
     * Creates new form NewStudent
     */
    public  DocGia() {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblBang.getModel();
        showDocGia();
    }
    
    private void showDocGia() {
        DocGiaList = StudentModify.findAll();
        tableModel.setRowCount(0);
        
        DocGiaList.forEach((docgia) -> {
            tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, docgia.getMaDocGia(), 
                docgia.getHoten(), docgia.getNgaySinh(), docgia.getQueQuan()});
        });
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmaDocGia = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtquequan = new javax.swing.JTextField();
        bntthem = new javax.swing.JButton();
        btnTimdg = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        txtngaysinh = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        btncl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));

        jLabel1.setText("Mã độc giả");

        jLabel2.setText("Họ tên :");

        jLabel4.setText("Địa chỉ :");

        jLabel5.setText("Ngày sinh :");

        txtmaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaDocGiaActionPerformed(evt);
            }
        });

        bntthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        bntthem.setText("Thêm");
        bntthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthemActionPerformed(evt);
            }
        });

        btnTimdg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnTimdg.setText("Tìm");
        btnTimdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimdgActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã độc giả", "Họ tên", "Ngày sinh", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tblBang);

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rs.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btncl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        btncl.setText("Close");
        btncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(txtmaDocGia)
                            .addComponent(txthoten)
                            .addComponent(txtquequan))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bntthem)
                .addGap(59, 59, 59)
                .addComponent(btnTimdg)
                .addGap(51, 51, 51)
                .addComponent(btnxoa)
                .addGap(66, 66, 66)
                .addComponent(btnreset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncl)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntthem)
                    .addComponent(btnTimdg)
                    .addComponent(btnxoa)
                    .addComponent(btnreset)
                    .addComponent(btncl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaDocGiaActionPerformed

    private void bntthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthemActionPerformed
           
    String madg = txtmaDocGia.getText();
    String inputDatA =  txtmaDocGia.getText();
    String inputDatB =  txthoten.getText();
    String inputDatC =  txtngaysinh.getText();
    String inputDatD =  txtquequan.getText();
  
try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
    Statement st = conn.createStatement();

    ResultSet rs = st.executeQuery("SELECT * FROM docgia WHERE madocgia='" + madg + "'");

    if (rs.next() ) {
    JOptionPane.showMessageDialog(null, "Mã độc giả đã có trong danh sách!");

                

    } else if(inputDatA.isEmpty() || inputDatB.isEmpty() || inputDatC.isEmpty()|| inputDatD.isEmpty()) {
        // Nếu không tìm thấy độc giả hoặc sách
             JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");

      
    }else{
         int MaDocGia = Integer.parseInt(txtmaDocGia.getText());
        String HoTen = txthoten.getText();
        String NgaySinh = txtngaysinh.getText();
        String QueQuan = txtquequan.getText();

       qltv.DocGia DG = new qltv.DocGia(MaDocGia, HoTen, NgaySinh, QueQuan);
        StudentModify.insert(DG);
        showDocGia();
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Lỗi thêm độc giả!");
}
        
   ///
      
    }//GEN-LAST:event_bntthemActionPerformed

    private void btnTimdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimdgActionPerformed
String input = JOptionPane.showInputDialog(this, "Nhập tên bạn muốn tìm");
if(input != null && input.length() > 0) {
            DocGiaList = StudentModify.findByFullname(input);
            
            tableModel.setRowCount(0);
        
            DocGiaList.forEach((docgia) -> {
                 tableModel.addRow(new Object[] {tableModel.getRowCount() + 1, docgia.getMaDocGia(), 
                docgia.getHoten(), docgia.getNgaySinh(), docgia.getQueQuan()});
            });
        } else {
            showDocGia();
        }
    }//GEN-LAST:event_btnTimdgActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblBang.getSelectedRow();
        if(selectedIndex >= 0) {
            qltv.DocGia DG = DocGiaList.get(selectedIndex);
           int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ???");
            if(option == 0) {
                StudentModify.delete(DG.getMaDocGia());
                showDocGia();
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
            txtmaDocGia.setText("");
            txthoten.setText("");
            txtngaysinh.setText("");
            txtquequan.setText("");
            
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclActionPerformed
        // TODO add your handling code here:
         setVisible(false);
               // new Home().setVisible(true);

       // this.dispose();
    }//GEN-LAST:event_btnclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntthem;
    private javax.swing.JButton btnTimdg;
    private javax.swing.JButton btncl;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmaDocGia;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtquequan;
    // End of variables declaration//GEN-END:variables
}
