package form;


import form.PhieuMuon;
import form.DocGia;
import form.Sach;
import form.DangNhap;
import static java.awt.GridBagConstraints.BOTH;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {



    
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        bntNewStudent = new javax.swing.JButton();
        bntNewBook = new javax.swing.JButton();
        bntStatistics = new javax.swing.JButton();
        bntIssueBook = new javax.swing.JButton();
        bntReturnBook = new javax.swing.JButton();
        bntLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGUIMail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntNewStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntNewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addbook.png"))); // NOI18N
        bntNewStudent.setText("Sách");
        bntNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(bntNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 132, -1));

        bntNewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-user.png"))); // NOI18N
        bntNewBook.setText("Độc giả");
        bntNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewBookActionPerformed(evt);
            }
        });
        getContentPane().add(bntNewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        bntStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/statistic.png"))); // NOI18N
        bntStatistics.setText("Thống kê");
        bntStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStatisticsActionPerformed(evt);
            }
        });
        getContentPane().add(bntStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, -1));

        bntIssueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addpm.png"))); // NOI18N
        bntIssueBook.setText("Phiếu mượn");
        bntIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIssueBookActionPerformed(evt);
            }
        });
        getContentPane().add(bntIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 150, -1));

        bntReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ptadd.png"))); // NOI18N
        bntReturnBook.setText("Phiếu trả");
        bntReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReturnBookActionPerformed(evt);
            }
        });
        getContentPane().add(bntReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        bntLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        bntLogout.setText("Logout");
        bntLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(bntLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnGUIMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/message.png"))); // NOI18N
        btnGUIMail.setText("Gửi Mail");
        btnGUIMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUIMailActionPerformed(evt);
            }
        });
        getContentPane().add(btnGUIMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 130, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeback.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogoutActionPerformed
        // TODO add your handling code here:
setVisible(false);
new DangNhap().setVisible(true);
    }//GEN-LAST:event_bntLogoutActionPerformed

    private void bntNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNewBookActionPerformed
        // TODO add your handling code here:
  //setVisible(false);
   new DocGia().setVisible(true);
    }//GEN-LAST:event_bntNewBookActionPerformed

    private void bntStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStatisticsActionPerformed
       //  setVisible(false);
    new Thongke().setVisible(true);
    }//GEN-LAST:event_bntStatisticsActionPerformed

    private void bntIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIssueBookActionPerformed
        // TODO add your handling code here:
       // setVisible(false);
           new PhieuMuon().setVisible(true);
    }//GEN-LAST:event_bntIssueBookActionPerformed

    private void bntReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReturnBookActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        new PhieuTra().setVisible(true);
        //this.dispose();
        
    }//GEN-LAST:event_bntReturnBookActionPerformed

    private void bntNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNewStudentActionPerformed
        // TODO add your handling code here:
        //   setVisible(false);
        new Sach().setVisible(true);
    }//GEN-LAST:event_bntNewStudentActionPerformed

    private void btnGUIMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUIMailActionPerformed
        // TODO add your handling code here:
        new GuiMail().setVisible(true);
    }//GEN-LAST:event_btnGUIMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntIssueBook;
    private javax.swing.JButton bntLogout;
    private javax.swing.JButton bntNewBook;
    private javax.swing.JButton bntNewStudent;
    private javax.swing.JButton bntReturnBook;
    private javax.swing.JButton bntStatistics;
    private javax.swing.JButton btnGUIMail;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
