package form;


import java.sql.DriverManager;
import java.sql.Connection;
//import controler.ConnectionMySQL;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class PhieuTra extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public PhieuTra() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaDOcgia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtHienTrang = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaDOcgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDOcgiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaDOcgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 32, 189, -1));

        jLabel1.setText("Mã độc giả");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 35, 80, -1));

        jLabel2.setText("Mã sách");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 75, -1, -1));

        jLabel3.setText("Ngày mượn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));
        getContentPane().add(txtNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, 190, -1));

        jLabel4.setText("Ngày trả");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 155, -1, -1));
        getContentPane().add(txtNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 155, 190, -1));

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 72, 190, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rs.png"))); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 101, -1, -1));

        jLabel5.setText("Hiện trạng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 200, 62, -1));
        getContentPane().add(txtHienTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 195, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDOcgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDOcgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDOcgiaActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
  /*      String madg= txtMaDOcgia.getText();
        String masach = txtMaSach.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
            Statement st =conn.createStatement();
            ResultSet rs = st.executeQuery("select * from PhieuMuon where MaSach='"+masach+"' and MaSinhVien='"+madg+"'");
            if(rs.next()){
                 txtNgayMuon.setText(rs.getString(5));
                txtNgayTra.setText(rs.getString(6));
                txtHienTrang.setText(rs.getString(7));
               txtMaDOcgia.setEditable(false);
                txtMaSach.setEditable(false);
               
            }else
                JOptionPane.showMessageDialog(null, "Mã độc giả hoặc mã sách không đúng");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi tìm phiếu!");
        }
        */
   String madg= txtMaDOcgia.getText();
       // String masach = txtMaSach.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
            Statement st =conn.createStatement();
            ResultSet rs = st.executeQuery("select * from PhieuMuon where MaSinhVien='"+madg+"'");
            if(rs.next()){
                 txtNgayMuon.setText(rs.getString(5));
                txtNgayTra.setText(rs.getString(6));
                txtHienTrang.setText(rs.getString(7));
               txtMaDOcgia.setEditable(true);
                txtMaSach.setText(rs.getString(2));
               
            }else
                JOptionPane.showMessageDialog(null, "Mã độc giả không đúng");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi tìm phiếu!");
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
   //setVisible(false);
   setVisible(false);
  // new Home().setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
          String madg= txtMaDOcgia.getText();
        String masach = txtMaSach.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
            Statement st =conn.createStatement();
            st.executeUpdate("update PhieuMuon set HienTrang ='Đã trả' where MaSach='"+masach+"' and MaSinhVien='"+madg+"'");
            JOptionPane.showMessageDialog(null, "Trả sách thành công!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi trả sách!");
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtHienTrang;
    private javax.swing.JTextField txtMaDOcgia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    // End of variables declaration//GEN-END:variables
}
