package form;

import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import controler.PhieuMuonModify;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.util.Date;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class PhieuMuon extends javax.swing.JFrame {// Chuyển đổi thành java.sql.Date
    // Đây là java.util.Date
    // Chuyển đổi thành java.sql.Date
    // Đây là java.util.Date

    DefaultTableModel tableModel;
    List<qltv.PhieuMuon> PhieuMuonList = new ArrayList<>();

    /**
     * Creates new form IssueBook
     */
    public PhieuMuon() {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblBangPhieuMuon.getModel();
        showPhieuMuon();
    }

    private void showPhieuMuon() {
        PhieuMuonList = PhieuMuonModify.findAll();
        tableModel.setRowCount(0);

        PhieuMuonList.forEach((pm) -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1,
                pm.getMaDocGia(), pm.getMaSach(), pm.getTenSach(), pm.getTenTacGia(), pm.getNgayMuon(), pm.getNgayTra()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JTextField();
        btnThemPhieuMuon = new javax.swing.JButton();
        btnTimdg = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangPhieuMuon = new javax.swing.JTable();
        txtMaSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        txtngayMuon = new com.toedter.calendar.JDateChooser();
        txtNgayTRa = new com.toedter.calendar.JDateChooser();
        lbl = new javax.swing.JLabel();
        txtHT = new javax.swing.JTextField();
        btbcl = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 97, -1));

        jLabel2.setText("Mã độc giả");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 9, 84, -1));

        jLabel4.setText("Ngày mượn");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, 24));

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rs.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 343, -1, -1));

        jLabel7.setText("Mã sách");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 79, -1));
        getContentPane().add(txtMaDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 441, -1));

        btnThemPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThemPhieuMuon.setText("Thêm phiếu mượn");
        btnThemPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuMuonActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 343, -1, -1));

        btnTimdg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnTimdg.setText("Tìm phiếu mượn");
        btnTimdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimdgActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 343, -1, -1));

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnxoa.setText("Xóa phiếu mượn");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 343, -1, -1));

        tblBangPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã độc giả", "Mã sách", "Tên sách", "Thể loại", "Ngày mượn", "Ngày phải trả", "Hiện trạng"
            }
        ));
        jScrollPane1.setViewportView(tblBangPhieuMuon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 416, 895, 260));
        getContentPane().add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 441, -1));

        jLabel3.setText("Ngày phải trả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 25));

        jLabel8.setText("Tên sách");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 65, -1));
        getContentPane().add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 441, -1));

        jLabel9.setText("Thể loại");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 65, -1));
        getContentPane().add(txtTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 441, -1));
        getContentPane().add(txtngayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 440, -1));
        getContentPane().add(txtNgayTRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 441, -1));

        lbl.setText("Hiện trạng");
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 72, -1));
        getContentPane().add(txtHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 441, -1));

        btbcl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close (1).png"))); // NOI18N
        btbcl.setText("Close");
        btbcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbclActionPerformed(evt);
            }
        });
        getContentPane().add(btbcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 343, -1, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        
        txtMaDG.setText("");
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtTheLoai.setText("");
        txtngayMuon.setDateFormatString(" ");
        txtNgayTRa.setDateFormatString("");
        
        

    }//GEN-LAST:event_btnresetActionPerformed

    private void btnThemPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuMuonActionPerformed
       
        String inputDatA =  txtMaDG.getText();
if (inputDatA.isEmpty() ||inputDatA.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ dữ liệu.");
} else {
    // Thêm dữ liệu vào bảng hoặc xử lý dữ liệu ở đây.


            // Thêm dữ liệu vào bảng hoặc xử lý dữ liệu ở đây.

          
            int madg = Integer.parseInt(txtMaDG.getText());
            int MASach = Integer.parseInt(txtMaSach.getText());
            String tensach = txtTenSach.getText();
            String theloai = txtTheLoai.getText();

            java.util.Date utilNgayMuon = txtngayMuon.getDate();
            java.sql.Date ngaymuon = new java.sql.Date(utilNgayMuon.getTime());

            java.util.Date utilNgayTra = txtNgayTRa.getDate();
            java.sql.Date ngaytra = new java.sql.Date(utilNgayTra.getTime());
            String htrang = txtHT.getText();

            //   float giaphieu = resultSet.getFloat("GiaPhieu");
            qltv.PhieuMuon pm = new qltv.PhieuMuon(madg, MASach, tensach, theloai, ngaymuon, ngaytra,htrang);
            PhieuMuonModify.insert(pm);
            showPhieuMuon();
}
    }//GEN-LAST:event_btnThemPhieuMuonActionPerformed

    private void btnTimdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimdgActionPerformed
        String input = JOptionPane.showInputDialog(this, "Nhập tên bạn muốn tìm");
       if (input != null && input.length() > 0) {
            PhieuMuonList = PhieuMuonModify.findByFullname(input);

            tableModel.setRowCount(0);

            PhieuMuonList.forEach((pm) -> {
                tableModel.addRow(new Object[]{tableModel.getRowCount() + 1,
                    pm.getMaDocGia(), pm.getMaSach(), pm.getTenSach(), pm.getTheLoai(), pm.getNgayMuon(), pm.getNgayTra(),pm.getHienTrang()});
            });
        } else {
            showPhieuMuon();
        }
    }//GEN-LAST:event_btnTimdgActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblBangPhieuMuon.getSelectedRow();
        if (selectedIndex >= 0) {
            qltv.PhieuMuon pm = PhieuMuonList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ???");
            if (option == 0) {
                PhieuMuonModify.delete(pm.getMaDocGia());
                showPhieuMuon();
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btbclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbclActionPerformed
        // TODO add your handling code here:
        setVisible(false);
                //new Home().setVisible(true);

       // this.dispose();
        
    }//GEN-LAST:event_btbclActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
 /*         
        String madg= txtMaDG.getText();
        String masach = txtMaSach.getText();
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
            Statement st =conn.createStatement();
            ResultSet rs = st.executeQuery("select * from Sach where MaSach='"+masach+"' " );
            ResultSet rsl = st.executeQuery("select * from docgia WHERE madocgia='" + madg + "'");
            if(rs.next() ){
                 txtTenSach.setText(rs.getString(2));
                txtTheLoai.setText(rs.getString(3));
            }else
                JOptionPane.showMessageDialog(null, "Mã độc giả hoặc mã sách không đúng");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi tìm phiếu!");
        }
        */
        
    String madg = txtMaDG.getText();
   String masach = txtMaSach.getText();

try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quanlythuvien", "root", "root");
    Statement st = conn.createStatement();

   // ResultSet rsSach = st.executeQuery("SELECT * FROM Sach WHERE MaSach='" + masach + "'");
    ResultSet rsDocGia = st.executeQuery("SELECT * FROM docgia WHERE madocgia='" + madg + "'");

    if (rsDocGia.next() ) {
    ResultSet rsSach = st.executeQuery("SELECT * FROM Sach WHERE MaSach='" + masach + "'");
         if(rsSach.next())
         {
              txtTenSach.setText(rsSach.getString(2));
        txtTheLoai.setText(rsSach.getString(3));
                JOptionPane.showMessageDialog(null, "Đã tìm thấy độc giả và sách.");

         }else{
              JOptionPane.showMessageDialog(null, "Không tìm thấy độc giả và sách.");
         }
        
    } else {
        // Nếu không tìm thấy độc giả hoặc sách
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ mã độc giả và mã sách!");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Lỗi tìm phiếu!");
}
    

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbcl;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemPhieuMuon;
    private javax.swing.JButton btnTimdg;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTable tblBangPhieuMuon;
    private javax.swing.JTextField txtHT;
    private javax.swing.JTextField txtMaDG;
    private javax.swing.JTextField txtMaSach;
    private com.toedter.calendar.JDateChooser txtNgayTRa;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    private com.toedter.calendar.JDateChooser txtngayMuon;
    // End of variables declaration//GEN-END:variables
}
